### ISSUE TITLE
unstable FlashAudioPlugin

### ISSUE THREAD

**Issue by krzysztof-o** [CreateJS/SoundJS#141]
Recently I've been playing with SoundJS and I have some problems using FlashAudioPlugin.
1. I was not able to change sound volume (only global volume)
2. Example "Flash only" doesn't work - no files on the list: http://www.createjs.com/#!/Demos/SoundJS/Audio-Test-Suite

**Comment by OJayRobinson** [comment]
Thanks for reporting this.  The problem is the swf file is not properly included on the website, which we will fix promptly.  The latest from the [git repos](https://github.com/CreateJS/SoundJS) should work properly if you'd to pull and run locally.

I've tested Instance volume in the TestSuite demo and it works for me locally.

Hope that helps.

**Comment by OJayRobinson** [comment]
The website has been updated, thanks for your help with this.
