### ISSUE TITLE
soundjs-NEXT: Internet Explorer 11: instance "complete" event

### ISSUE THREAD

**Issue by wintersw** [CreateJS/SoundJS#166]
add several instances of one file - all paused
start a single instance.. wait for complete
if completed -> the complete event is dispatched for all files

**Comment by OJayRobinson** [comment]
yes, this is intentional behavior.

SoundJS will only load a file once, and then internally shares that resource rather than loading it a second time.  When you register multiple copies of the same file, once it finishes loading one it will fire a load event for all of them since they are all considered loaded and ready to be used.

SoundJS internal loading does not have a pause feature.

**Comment by wintersw** [comment]
wow.. that was fast.. thanks!
But I'm not talking about the load event but the complete event (playing)

**Comment by OJayRobinson** [comment]
derp, sorry about that.

I ran a quick test using the latest SoundJS-NEXT in IE 11.0.9600.17801 on win 8.1 and could not replicate this issue.

If you want to throw together a small code sample that demonstrates the issue, I can look into it further.

Hope that helps.

**Comment by wintersw** [comment]
hello,
took me some time to figure out why our unit tests are not passing and it seams to be an existing issue but our tests were not detailed enough to get me in the right direction
You can find the source at
https://drive.google.com/file/d/0Bxh4Et_mXDVUM2hIc3pzMThIdFk/view?pli=1
including a detaild issue description (README.txt)
The issue already exists in 0.6.x and is cross-browser: pausing multiple playing instances

**Comment by OJayRobinson** [comment]
The problem is you've created a race condition by placing the pause inside of the succeeded event handler.  If you move the pause to the start of the instanceStartPlaying function, everything works as expected.  I would strongly advise against altering the playstate of a sound instance inside of the succeeded event, as it logically doesn't make sense and can lead to unexpected errors and states.

Hope that helps.
