### ISSUE TITLE
instance.destinationNode and instance.context are null

### ISSUE THREAD

**Issue by raldred** [CreateJS/SoundJS#169]
I've just updated a project from 0.5.3 to 0.6.1
I'm having trouble re-wiring a web audio instance.

I'm emulating 3d positional audio.
Soundjs it's wired like so:
source -> panner -> gain -> masterGain

In order for HRTF to work so we can get true 3d sound the nodes need to be wired like so:
source -> gain -> panner -> masterGain

Here's my 0.5 implementation

		# grab the current nodes
		source = instance.sourceNode
		panner = instance.panNode
		volume = instance.gainNode
		masterVolume = instance._owner.gainNode
 		
 		# superior model for panning
 		panner.panningModel = 'HRTF'

		# disconnect
		source.disconnect(0)
		panner.disconnect(0)
		volume.disconnect(0)

		# re-wire in the correct order
		source.connect(volume)
		volume.connect(panner)
		panner.connect(masterVolume)

instance._owner is no longer available and looking at the latest versions destinationNode is the master GainNode but both that and context are null so I'm not sure how to get them connected, anyone?

Thanks

**Comment by OJayRobinson** [comment]
Hi Rob, up to your usual shenanigans I see.

Master GainNode, context, and panningModel are all available on the static WebAudioSoundInstance class now.

Master GainNode is [createjs.WebAudioSoundInstance.destinationNode](http://www.createjs.com/docs/soundjs/classes/WebAudioSoundInstance.html#property_destinationNode).

Context is [createjs.WebAudioSoundInstance.context](http://www.createjs.com/docs/soundjs/classes/WebAudioSoundInstance.html#property_context).

Panning model is [createjs.WebAudioSoundInstance._panningModel](http://www.createjs.com/docs/soundjs/classes/WebAudioSoundInstance.html#property__panningModel) and you only need to set it once, before you create any SoundInstances.  It's also worth nothing in older implementations of web audio it will be a number instead of a string.

If you didn't need to change the order of the nodes, you could just change the panning model once and be done.  Hope that helps. =)

**Comment by raldred** [comment]
Hey OJay,
Haha yes always trying to do things out of the ordinary here.

I failed see that little static label in the docs.
I was trying to access it on an instance.

Fixed :+1:
