### ISSUE TITLE
Problems with loading sounds in Opera Next

### ISSUE THREAD

**Issue by a-ignatov-parc** [CreateJS/SoundJS#210]
One of the Opera's updates has broken sound preloading. On any attempt SoundJS throws `fileerror`. You can see this problem in your demo http://www.createjs.com/demos/soundjs/webaudionodeinsertion

I have found workaround by not installing SoundJS plugin for `LoadQueue`.

```javascript
var queue = new createjs.LoadQueue();
queue.installPlugin(createjs.Sound); // If disable this line everything loads fine
queue.stopOnError = true;
```

P.S. Opera version that was tested is `32.0.1948.69`

**Comment by a-ignatov-parc** [comment]
https://github.com/CreateJS/SoundJS/issues/202 issue sounds like same problem.

**Comment by a-ignatov-parc** [comment]
The only difference that i have found is that SoundJS plugin use `prefereXHR`, and built in loader in PreloadJS doesn't use it or at least it can be configured

**Comment by a-ignatov-parc** [comment]
I forget to notice that sounds stop playing after disabling sound plugin

**Comment by a-ignatov-parc** [comment]
The only that has helped to solve loading issue in Opera is to configure loading `wav` files prior to `mp3`

**Comment by lannymcnie** [comment]
PreloadJS can only load HTMLAudio tags, since the logic to store and play WebAudio is very specific to the playback engine, so it is contained in SoundJS. 

I did some testing, and as you pointed out above, the order of the audio formats is important. This is due to incorrect reporting of MP3 playback in Opera. The demo you referenced is a simple WebAudio visualizer, which only has an MP3 source. By swapping in an OGG, it works fine. It is therefore recommended to prioritize OGGs for Opera as well.

The documentation notes a similar issue in FireFox:
> mp3 audio files do not load properly on all windows machines, reported at  https://bugzilla.mozilla.org/show_bug.cgi?id=929969. For this reason it is recommended to pass another  FF supported type (ie ogg) first until this bug is resolved, if possible.

Note that OGG is a better format than WAV due to filesize.
