### ISSUE TITLE
Alarm not fire in iOS on iPhone/iPad

### ISSUE THREAD

**Issue by sirshurf** [CreateJS/SoundJS#234]
Hi all,
I am getting nuts a little bit.
I have this link:
http://online-timer.en.downloadastro.com/tools/?PageSpeed=off#5000

But the alarm not working in iOS, it works perfectly in Android and PC. Works ok on my MacBook... but not on the iPhone.
Please advice

**Comment by lannymcnie** [comment]
Sorry, this is an iOS limitation.

This issue is because you must "unlock" the web audio context on iOS using a mousedown/touchend event. In SoundJS 0.6.2, any document-level click/touchend will do it (so there is nothing extra you need to do yourself). Earlier versions required you to do some additional manual steps (which you can still see in the [MobileSafe demo in GitHub](http://www.createjs.com/tutorials/Mobile%20Safe%20Approach/), which is not necessary any more).

Since you are using SoundJS 0.6.2, as long as you click somewhere in the document, the audio will work. I tested your demo on an iPod running iOS9, and was able to hear the alarm audio if I tapped the document before the timer expired.
