### ISSUE TITLE
can't get the test page running on my server

### ISSUE THREAD

**Issue by miltnerunit** [CreateJS/SoundJS#257]
http://www.kristinmiltner.net/MasterExamplesTestSuite.html?type=normal 

This is most likely not a bug, but a user error. 

I get: 'SoundJS is not currently supported in your browser', though it's Chrome on Mac Yosemite and I'm using soundJS on another page with no problems. I simply copied the test suite into a new HTML doc and put that in my public_html directory. What else do I need to do/include?

**Comment by lannymcnie** [comment]
The test suite shows this error when the `Sound.isReady()` method returns `false` -- which happens when there is no activePlugin. 

The demo you posted above has a ton of 404 errors, including SoundJS.

The demo will try to initiate the plugins based on the url parameters:
* "flash" will be Flash-only
* "html5" will use the HTML5Audio (tag-based) plugin only
* Otherwise the default set (WebAudio, then HTML5, then Flash) will be requested.

If you pass "normal", then the 3rd option should occur. SoundJS will attempt to instantiate each plugin in order until one succeeds. If you have properly included the SoundJS script (check your console for errors), then all 3 plugins may be reporting that they are not supported.

I am closing this for now. If you correct the 404 errors, and it still won't work, let me know here, and I can check it out again.
